DROP TABLE USER IF EXISTS;
CREATE TABLE USER (
id INTEGER NOT NULL AUTO_INCREMENT,
username VARCHAR(128) NOT NULL UNIQUE,
password VARCHAR (128) NOT NULL ,
-- roles VARCHAR (128) NOT NULL ,
name VARCHAR (128) NOT NULL ,
lastname VARCHAR (128) NOT NULL ,
city VARCHAR (128) NOT NULL ,
car_Licence_Id VARCHAR (128) NOT NULL ,
email_Adress VARCHAR (128) NOT NULL ,
phone_Number  varchar (128) NOT NULL ,
wallet  varchar (128) NOT NULL ,
PRIMARY KEY (id)
);